.TH "/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/contactbdd.h" 3 "Jeudi 16 Décembre 2021" "DoxygenFinal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/contactbdd.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <contact\&.h>\fP
.br
\fC#include <QDate>\fP
.br
\fC#include <QtSql/QSqlDatabase>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QtSql/QSqlQuery>\fP
.br
\fC#include <list>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <string>\fP
.br
\fC#include <QVariant>\fP
.br
\fC#include <QSql>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContactBDD\fP"
.br
.RI "Classe qui gère la base de donnée La classe herite d'un \fBQObject\fP, permet de créer des fonctions et des structures qui dialogue avec notre base d'où la création des fonctions CRUD(Create,Read,Update,Delete) et recherche \&. "
.in -1c
.SH "Description détaillée"
.PP 

.PP
\fBAuteur\fP
.RS 4
BARRY Thierno Oumar & DIALLO Iliassou la connexion Qt à un base sqlite qui stocke les informations relatives à un contact 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DoxygenFinal à partir du code source\&.
