.TH "/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/Date.h" 3 "Jeudi 16 Décembre 2021" "DoxygenFinal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/Date.h
.SH SYNOPSIS
.br
.PP
\fC#include <ctime>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDate\fP"
.br
.RI "la classe reprensentant la \fBDate\fP La classe date nous permet de definir la date courante et les differentes utilisations que nous auront a faire\&. "
.in -1c
.SH "Description détaillée"
.PP 

.PP
\fBAuteur\fP
.RS 4
BARRY Thierno & Diallo Iliassou 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DoxygenFinal à partir du code source\&.
