.TH "/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/fenetreprincipale.h" 3 "Jeudi 16 Décembre 2021" "DoxygenFinal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/fenetreprincipale.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include 'contact\&.h'\fP
.br
\fC#include <contactbdd\&.h>\fP
.br
\fC#include <interactionbdd\&.h>\fP
.br
\fC#include 'Interaction\&.h'\fP
.br
\fC#include 'Todo\&.h'\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QTextEdit>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QTimeEdit>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QDateEdit>\fP
.br
\fC#include <QFormLayout>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <QComboBox>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <list>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QDate>\fP
.br
\fC#include <string>\fP
.br
\fC#include <QTextDocument>\fP
.br
\fC#include <QRegularExpression>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QTextBlock>\fP
.br
\fC#include <QJsonDocument>\fP
.br
\fC#include <QIODevice>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QJsonObject>\fP
.br
\fC#include <QJsonArray>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFenetrePrincipale\fP"
.br
.RI "Classe qui gère la fenetre principale \&. La classe herite d'une \fBQMainWindow\fP,elle est l'une des plus importante pour notre projet car elle permet de faire la déclaration des boites de dialogues ,des slots,des signaux pour bien gérer l'interconnections entre les classes et les bases de données \&. "
.in -1c
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 

.PP
\fBAuteur\fP
.RS 4
BARRY Thierno Oumar & DIALLO Iliassou 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DoxygenFinal à partir du code source\&.
