.TH "/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/interactionbdd.cpp" 3 "Jeudi 16 Décembre 2021" "DoxygenFinal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/interactionbdd.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'interactionbdd\&.h'\fP
.br

.SH "Description détaillée"
.PP 

.PP
\fBAuteur\fP
.RS 4
BARRY Thierno Oumar & DIALLO Iliassou 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DoxygenFinal à partir du code source\&.
