.TH "/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/Interaction.h" 3 "Jeudi 16 Décembre 2021" "DoxygenFinal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/Interaction.h
.SH SYNOPSIS
.br
.PP
\fC#include <ostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Date\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInteraction\fP"
.br
.RI "La classe permet de gerer une interaction suivant son contenu et sa date de creation\&. "
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DoxygenFinal à partir du code source\&.
