.TH "/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/Interaction.cpp" 3 "Jeudi 16 Décembre 2021" "DoxygenFinal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/Interaction.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Interaction\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBInteraction\fP &action)"
.br
.RI "Affichage de l'intéraction \&. "
.in -1c
.SH "Description détaillée"
.PP 

.PP
\fBAuteur\fP
.RS 4
BARRY Thierno Oumar & DIALLO Iliassou 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP

.SH "Documentation des fonctions"
.PP 
.SS "std:: ostream& operator<< (std::ostream & o, const \fBInteraction\fP & action)"

.PP
Affichage de l'intéraction \&. L'affichage d'une Intéraction\&.
.PP
\fBParamètres\fP
.RS 4
\fIstd,:\fP ostream &o :la bibliothèque ostream qui permet l'affichage 
.br
\fIconst\fP \fBInteraction\fP& action:l'intéraction à afficher\&. 
.RE
.PP
\fBRenvoie\fP
.RS 4
o : pour l'affichage de l'intéraction càd sa date et son contenu \&. 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DoxygenFinal à partir du code source\&.
