.TH "main" 3 "Jeudi 16 Décembre 2021" "DoxygenFinal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main \- La classe main La classe qui est la plus importante car elle permet de faire la connection de la fenetre principale à la base de donnée et aussi elle nous permet d'afficher les interfaces \&.  

.SH SYNOPSIS
.br
.PP
.SH "Description détaillée"
.PP 
La classe main La classe qui est la plus importante car elle permet de faire la connection de la fenetre principale à la base de donnée et aussi elle nous permet d'afficher les interfaces \&. 


.PP
\fBParamètres\fP
.RS 4
\fIint\fP argc : l'entier en parametre \&. 
.br
\fIchar\fP *argv[] : la chaine de caractère en paramètre \&. 
.RE
.PP


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DoxygenFinal à partir du code source\&.
