.TH "/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/Todo.h" 3 "Jeudi 16 Décembre 2021" "DoxygenFinal" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/diallo/Bureau/CDAA/Projet/ProjetQt/ProjetFinalCDAA/Todo.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Date\&.h'\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTodo\fP"
.br
.RI "cette classe permet de gerer une tache suivant son contenu et sa date de creation "
.in -1c
.SH "Description détaillée"
.PP 

.PP
\fBAuteur\fP
.RS 4
BARRY Thierno Oumar & DIALLO Iliassou 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour DoxygenFinal à partir du code source\&.
